### ISSUE TITLE
Create homepage

### ISSUE THREAD

**Issue by uni-mairata** [uni-mairata/uni-mairata.github.io#2]

**Comment by junaidahamed800** [comment]
@uni-mairata Hi i am new to open source contribution can i contribute to this project ? . i am good at frontend ( HTML CSS JS(basics) )

**Comment by uni-mairata** [comment]
@junaidahamed800 Hi! Sorry, I've barely started on this project so the issues are basically just a personal to-do list for myself. I need to actually figure out what I want to do with the website first.

**Comment by uni-mairata** [comment]
Completed
